#!/usr/bin/env bash
# Regenerate dashboard JSONs and push them to GitHub.
# Called by scripts/cron_eod_v4.sh @ 20:00 IST.
#
# Idempotent: if nothing changed, just exits 0 with "nothing to commit".

set -uo pipefail

DASH_DIR="/Users/kshitijbanka/Documents/lattice/dashboard"
PY="/Users/kshitijbanka/Documents/lattice/.venv/bin/python"

cd "$DASH_DIR"

echo "--- [refresh] regenerating JSONs ---"
"$PY" generate_data.py 2>&1 | tail -8

if ! git diff --quiet data/ ; then
    DATE_TAG=$(date '+%Y-%m-%d %H:%M IST')
    echo
    echo "--- [refresh] data/ changed, committing ---"
    git add data/
    git commit -m "EOD refresh — ${DATE_TAG}

Auto-generated by dashboard/refresh_and_push.sh.

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>" 2>&1 | tail -3
    echo
    echo "--- [refresh] pushing to origin/main ---"
    git push origin main 2>&1 | tail -5
    echo "  ✓ pushed — Streamlit Cloud will auto-redeploy in ~30 sec"
else
    echo
    echo "--- [refresh] no data/ changes, nothing to push ---"
fi
